version: "3.8"
services:
 catalogdb:
   container_name: catalogdb
   restart: always
   ports:
     - "27017:27017"
   volumes:
     catalogdb_volume:/data/db
 basketdb:
   container_name: basketdb
   restart: always
   ports:
     - "6379:6379"
 discount:
   container_name: discountdb
   restart: always
   ports:
     - "5432:5432"
   volumes:
     discount_volume:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=Password123.
     - POSTGRES_DB=postgres
 identitydb:
   container_name: identitydb
   restart: always
   ports:
     - "1433:1433"
   volumes:
     identitydb_volume:/var/opt/mssql/data
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password123.
 orderdb:
   container_name: orderdb
   restart: always
   ports:
     - "1455:1455"
   volumes:
     orderdb_volume:/var/opt/mssql/data
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password123.
 rabbitmq:
   container_name: rabbitmq
   restart: always
   ports:
     - "5672:5672"
     - "15672:15672"